# Kanika Sharma - 2024TM93011
# Jaeger Configuration - LMO Stack

service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]

extensions:
  healthcheckv2:
    use_v2: true
    http:
      endpoint: 0.0.0.0:13133
  jaeger_query:
    storage:
      traces: memory_backend
      metrics: metrics_backend
    base_path: /jaeger/ui
  jaeger_storage:
    backends:
      memory_backend:
        memory:
          max_traces: 5000
    metric_backends:
      metrics_backend:
        prometheus:
          endpoint: "http://prometheus:9090"
          normalize_calls: true
          normalize_duration: true

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: memory_backend
